name: Test Plugin
description: I MUST TEST
author: Datamancer
website: http://www.war-torn.net/forums/index.php
main: com.tofurkishrobocracy.testplugin.TestPlugin
version: 0.1
commands:
  makewall:
    description: Allows you to make a big wall
    usage: "Usage: '/makewall help'"